language: node_js

sudo: false

node_js:
  - "node"

os:
- linux

matrix:
  include:
    - os: osx
      env: COMPILER=clang++
      osx_image: xcode9.2
      compiler: clang
    - os: linux
      env: CXX=clang-3.6
      compiler: clang-3.6

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6

script:
  - npm test

branches:
  only:
    - prebuild_support_test
    - /^v.*$/

deploy:
  provider: script
  script: npm run prebuild && npm run prebuild:upload -u ${PREBUILD_UPLOAD}
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
